prode_homepage:
    path:     /
    defaults: { _controller: ProdeBundle:Default:index }

prode_pronosticos:
    path:     /pronosticosGrupos
    defaults: { _controller: ProdeBundle:Default:pronosticosGrupos }    

registro:
    path:     /registro
    defaults: { _controller: FOSUserBundle:Registration:register }    

login:
    path:     /login
    defaults: { _controller: FOSUserBundle:Security:login}  

logout:
    path:     /logout
    defaults: { _controller: FOSUserBundle:Security:logout}      