prode_homepage:
    path:     /
    defaults: { _controller: ProdeBundle:Default:index }

calcular:
    path:     /calcular
    defaults: { _controller: ProdeBundle:Default:calcular }

prode_pronosticos:
    path:     /guardar_pronosticos
    defaults: { _controller: ProdeBundle:Default:guardarPronosticos } 

guardar_resultados:
    path:     /guardar_resultados
    defaults: { _controller: ProdeBundle:Default:guardarResultados }     

grupo:
    path:     /grupo/{grupo}
    defaults: { _controller: ProdeBundle:Default:grupo }    

verTodos:
    path:     /todos
    defaults: { _controller: ProdeBundle:Default:verTodosPronosticos }  

grupoA:
    path:     /grupo/A
    defaults: { _controller: ProdeBundle:Default:grupo } 

registro:
    path:     /registro
    defaults: { _controller: FOSUserBundle:Registration:register }    

login:
    path:     /login
    defaults: { _controller: FOSUserBundle:Security:login }      

logout:
    path:     /logout
    defaults: { _controller: FOSUserBundle:Security:logout }       

guardar_grupo:
  pattern:  /guardarGrupo
  defaults: { _controller: ProdeBundle:Default:guardarGrupo }

generar_pronosticos:
  pattern: /gp
  defaults: { _controller: ProdeBundle:Default:generarPronosticos }