prode_homepage:
    path:     /
    defaults: { _controller: ProdeBundle:Default:index }

prode_pronosticos:
    path:     /pronosticosGrupos
    defaults: { _controller: ProdeBundle:Default:pronosticosGrupos } 

grupo:
    path:     /grupo/{grupo}
    defaults: { _controller: ProdeBundle:Default:grupo }    

grupoA:
    path:     /grupo/A
    defaults: { _controller: ProdeBundle:Default:grupo } 

registro:
    path:     /registro
    defaults: { _controller: FOSUserBundle:Registration:register }    

login:
    path:     /login
    defaults: { _controller: FOSUserBundle:Security:login }      

logout:
    path:     /logout
    defaults: { _controller: FOSUserBundle:Security:logout }       

guardar_grupo:
  pattern:  /guardarGrupo
  defaults: { _controller: ProdeBundle:Default:guardarGrupo }