prode:
    resource: "@ProdeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@ProdeBundle/Controller/'
    type: annotation

pagina_ayuda:
  pattern: /ayuda
  defaults: { _controller: ProdeBundle:Default:ayuda }
  requirements:
        _method: GET

portada:
  pattern: /
  defaults: { _controller: ProdeBundle:Default:portada }
  requirements:
        _method: GET        


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile